### ISSUE TITLE
It opens a second tab that asks to confirm delete of newly uploaded file?

### ISSUE THREAD

**Issue by nathan323** [DBjelovuk/ImgurUploader#1]
Is this necessary? Can this be turned off?

**Comment by bdrazen** [comment]
I can definitely add a setting to disable the delete tab, but note that it currently only pops up if you don't have a linked account, reason being there'd be no way to delete the file otherwise.

**Comment by nathan323** [comment]
Got it, thanks.

**Comment by bdrazen** [comment]
Latest release includes added toggle to disable deletion window for anonymous uploads (as well as another to disable uploading multiple files as album). Cheers. 👍
