### ISSUE TITLE
Upload more than 15 Images at once

### ISSUE THREAD

**Issue by TheTou** [DBjelovuk/ImgurUploader#3]
It seems there is a limit to how many Images you can upload at once. When I select more than 15 Images the context menu entry disappears. Is it possible to disable this limit or at least increase it? Thanks!

**Comment by bdrazen** [comment]
Seems this is default windows behaviour for the context menu. The threshold can apparently be adjusted from the registry though:

https://support.microsoft.com/en-au/help/2022295/context-menus-are-shortened-when-more-than-15-files-are-selected
